version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8070:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master port
    volumes:
      #- ./data:/data  # Volume para dados compartilhados
      - type: bind
        source: /mnt/sdb_04/doc_file
        target: /mnt

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
        SPARK_WORKER_CORES: 1
        SPARK_WORKER_MEMORY: 2g

    depends_on:
      - spark-master
    ports:
      - "8071:8081"  # Spark Worker UI
    volumes:
      #- ./data:/data  # Volume para dados compartilhados
      - type: bind
        source: /mnt/sdb_04/doc_file
        target: /mnt